apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-app
  labels:
    app: stateless-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateless-app
  template:
    metadata:
      labels:
        app: stateless-app
    spec:
      containers:
        - name: stateless-app
          image: 804903994046.dkr.ecr.eu-west-2.amazonaws.com/stateless-app:latest
          ports:
            - containerPort: 80